-- Add new columns to portfolio_metrics_snapshot for advanced metrics
ALTER TABLE portfolio_metrics_snapshot
ADD COLUMN IF NOT EXISTS industry_pe DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS industry_pb DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS div_yield DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS eps DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS roe DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS roce DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS risk_label VARCHAR(64);
