-- Instrument Metrics Table
CREATE TABLE instrument_metrics (
    isin VARCHAR(12) NOT NULL,
    ticker VARCHAR(32),
    sector VARCHAR(64),
    industry VARCHAR(64),
    sub_industry VARCHAR(64),
    market_cap DOUBLE PRECISION,
    market_cap_rank BIGINT,
    market_cap_label VARCHAR(32),
    pe_ratio DOUBLE PRECISION,
    pb_ratio DOUBLE PRECISION,
    industry_pe DOUBLE PRECISION,
    industry_pb DOUBLE PRECISION,
    eps DOUBLE PRECISION,
    div_yield DOUBLE PRECISION,
    roe DOUBLE PRECISION,
    roce DOUBLE PRECISION,
    high_52_week DOUBLE PRECISION,
    low_52_week DOUBLE PRECISION,
    high_all_time DOUBLE PRECISION,
    low_all_time DOUBLE PRECISION,
    beta DOUBLE PRECISION,
    alpha DOUBLE PRECISION,
    risk_label VARCHAR(32),
    num_shareholders BIGINT,
    creation_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updation_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    source VARCHAR(32),
    PRIMARY KEY (isin)
);
